# Generated by Django 3.2.4 on 2021-06-29 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=5)),
                ('abbreviation', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dose1_count', models.IntegerField()),
                ('dose2_count', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
                ('published_on', models.DateTimeField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vaccine')),
            ],
        ),
    ]
