# Generated by Django 3.2.4 on 2021-07-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210702_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationreport',
            name='id',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
