# Generated by Django 3.2.4 on 2021-07-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_vaccinationreport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agtestsreport',
            name='negatives_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agtestsreport',
            name='negatives_sum',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agtestsreport',
            name='positives_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agtestsreport',
            name='positives_sum',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agtestsreport',
            name='positivity_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bedsreport',
            name='capacity_all',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bedsreport',
            name='capacity_covid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bedsreport',
            name='free_all',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bedsreport',
            name='occupied_jis_covid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bedsreport',
            name='occupied_o2_covid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bedsreport',
            name='occupied_oaim_covid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bedsreport',
            name='occupied_other_covid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospitalstaffreport',
            name='out_of_work_ratio_doctor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hospitalstaffreport',
            name='out_of_work_ratio_nurse',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hospitalstaffreport',
            name='out_of_work_ratio_other',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patientsreport',
            name='confirmed_covid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientsreport',
            name='non_covid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientsreport',
            name='suspected_covid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientsreport',
            name='ventilated_covid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationreport',
            name='dose1_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationreport',
            name='dose2_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
