# Generated by Django 3.2.4 on 2021-06-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=16)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
            ],
        ),
        migrations.RenameField(
            model_name='vaccinationreport',
            old_name='region',
            new_name='region_id',
        ),
        migrations.RenameField(
            model_name='vaccinationreport',
            old_name='vaccine',
            new_name='vaccine_id',
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccinationreport',
            name='dose1_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccinationreport',
            name='dose2_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccinationreport',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccinationreport',
            name='published_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PatientsReport',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ventilated_covid', models.PositiveIntegerField()),
                ('non_covid', models.PositiveIntegerField()),
                ('confirmed_covid', models.PositiveIntegerField()),
                ('suspected_covid', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField()),
                ('published_on', models.DateField()),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStaffReport',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('out_of_work_ratio_doctor', models.FloatField()),
                ('out_of_work_ratio_nurse', models.FloatField()),
                ('out_of_work_ratio_other', models.FloatField()),
                ('updated_at', models.DateTimeField()),
                ('published_on', models.DateField()),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.district'),
        ),
        migrations.CreateModel(
            name='BedsReport',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('capacity_all', models.PositiveIntegerField()),
                ('free_all', models.PositiveIntegerField()),
                ('capacity_covid', models.PositiveIntegerField()),
                ('occupied_jis_covid', models.PositiveIntegerField()),
                ('occupied_oaim_covid', models.PositiveIntegerField()),
                ('occupied_o2_covid', models.PositiveIntegerField()),
                ('occupied_other_covid', models.PositiveIntegerField()),
                ('reported_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('published_on', models.DateField()),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='AgTestsReport',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('positivity_rate', models.FloatField()),
                ('positives_count', models.PositiveIntegerField()),
                ('negatives_count', models.PositiveIntegerField()),
                ('positives_sum', models.PositiveIntegerField()),
                ('negatives_sum', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField()),
                ('published_on', models.DateField()),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.district')),
            ],
        ),
    ]
