# Generated by Django 3.2.4 on 2021-06-30 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210630_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agtestsreport',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='bedsreport',
            old_name='hospital_id',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='hospitalstaffreport',
            old_name='hospital_id',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='patientsreport',
            old_name='hospital_id',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='vaccinationreport',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='vaccinationreport',
            old_name='vaccine_id',
            new_name='vaccine',
        ),
    ]
