# Generated by Django 3.2.4 on 2021-07-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_hospital_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
