# Generated by Django 3.2.4 on 2021-07-05 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210704_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaffreport',
            name='reported_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientsreport',
            name='reported_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
