# Generated by Django 3.2.4 on 2021-07-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210705_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsreport',
            name='reported_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hospitalstaffreport',
            name='reported_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patientsreport',
            name='reported_at',
            field=models.DateTimeField(null=True),
        ),
    ]
